### ISSUE TITLE
Consider switching to wheel installer format

### ISSUE THREAD

**Issue by SebastianoF** [SebastianoF/bruker2nifti#10]

**Comment by dzhoshkun** [comment]
1. To build the wheel: `python setup.py bdist_wheel`
1. Then look at the created `dist` directory, there should be a file ending in `.whl` there
1. Submit this to PyPI: `twine upload dist/bruker2nifty-0.1.0-XYZ.whl`

**Comment by SebastianoF** [comment]
Done. Now version 1.0.0 pip installable through wheel installer format.
