### ISSUE TITLE
Consider removing __all__ from package declaration

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#13]
The [`__all__` keyword](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) serves the following purpose:

> if a package’s `__init__.py` code defines a list named `__all__`, it is taken to be the list of module names that should be imported when from package import * is encountered

However the two `__all__` clauses in bruker2nifti explicitly declare all the modules currently. As such, they seem redundant to me.

**Comment by SebastianoF** [comment]
Uhm... I was following [this](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html) explanation, and it seems the __all__ should be written manually. 
Also the numpy.__init__.py seems to [add it]( https://github.com/numpy/numpy/blob/master/numpy/__init__.py)
Why did you say there are two of them? One is defined implicitly by default?

**Comment by dzhoshkun** [comment]
re "two instances":
1. https://github.com/SebastianoF/bruker2nifti/blob/master/bruker2nifti/__init__.py#L4
1. https://github.com/SebastianoF/bruker2nifti/blob/master/bruker2nifti/parsers/__init__.py#L1

**Comment by dzhoshkun** [comment]
re "[this](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html) explanation": it doesn't say anything different from the tutorial on the Python website (the link in my post) -- if the two were different, I'd follow the Python docs as they are the official ones, and also up-to-date (the other one is from 2012).

In any case, `__all__` makes a difference only when someone does an import of the form `from bruker2nifti import *`: only those modules listed explicitly under the `__all__` clause get imported then.
