### ISSUE TITLE
Dead links in the README

### ISSUE THREAD

**Issue by rougier** [SebastianoF/bruker2nifti#17]
There are some dead (or faulty) links in the README:

* http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/
* https://github.com/SebastianoF/bruker2nifti/blob/master/bruker2nifti.rtfd.io

Also, is it "Mattew Brett" or "Matthew Brett" ?

**Comment by SebastianoF** [comment]
Typo and link corrected, thanks! Do you think the README is too pedantic? Maybe there is too much in there.

**Comment by rougier** [comment]
No I think it's fine. What is not clear is what difference do you make with develop install and pyenv install. You have two lines with `pip install bruker2nifti` such that in the end it is not clear which one to use actually.

Also, you seem to imply that the only requirement is python 2.7, but you also need bumpy, no?

**Comment by SebastianoF** [comment]
I added some links to the requirements.txt file and to the development mode so to try to make things clear. The code actually works also with python 3. Is 2.7+ understood in this way?

**Comment by rougier** [comment]
Not al all. For me, it was not working with Python 3. You should mention it explicitly.

**Comment by SebastianoF** [comment]
Yes, the released version is still only for Python 2.7. How to mange the discrepancy between the release version and the current version? Can I propose a new release on Pypi while under review?

**Comment by SebastianoF** [comment]
Maybe this is a question for the editor, will open a new issue for this!
