### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TheChymera** [SebastianoF/bruker2nifti#2]
Hello,

The author of [Bru2Nii](https://github.com/neurolabusc/Bru2Nii) has recommended your package, but I notice it does not have any release version yet, and the wiki landing page is quite ominous.

I would like to package your software for Gentoo when it's released, could you notify me about that when it happens?

Not least of all, do you have a CLI for the convertor? or a main python function one can call, or better yet, do you have a nipype interface already written?

**Comment by SebastianoF** [comment]
It is a very good idea to wrap in in nipype. I wanted actually to add it directly as a nibabel feature. 

Still there is a big note of caution - the same reported in the wiki page!
Before making it that widely available I wanted to have some more users working on it, try and testing and reporting bugs. 
Converting from Bruker is not that straightforward, and the code must go trough some more refactoring. There are still some issues, as for example in the translational part, of the affine transformation when parsing. 
It is working for the dataset I am getting for my project. Making it general will need some more work. 
So... Feel free to try to run it on your machine and see if it works for your data! :-) !

**Comment by SebastianoF** [comment]
bruker2nifti now on PyPI. You can try and install it with pip (after having installed the libraries in requirements.txt).
Then follow the example https://github.com/SebastianoF/bruker2nifti/wiki/Examples, and let me know if everything works!
