### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by rougier** [SebastianoF/bruker2nifti#21]
Is it possible to have tooltip explaining what are the different checkboxes or is it too much work?
This might be the limit of my expertise for the review but I found the GUI a bit "raw". A simple "help" button explaining things could help.

**Comment by SebastianoF** [comment]
The GUI is raw rather for limits in using tkinter.
I added the help button redirecting to the documentation in the development version.
You can check it out installing in development mode. Will be included in the next release!
