### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rougier** [SebastianoF/bruker2nifti#22]
The `index.rst` could benefit from an introduction (re-using the README) explaining the goal of the library, how to use, pointers to the GitHub repository, external links, etc). 

A usage section using real-data would be also welcome.

**Comment by SebastianoF** [comment]
Uhm... The content of the docs folder is created by sphinx automatically to produce the API documentation
[http://bruker2nifti.readthedocs.io/en/latest/](http://bruker2nifti.readthedocs.io/en/latest/)
I am not sure if the folder docs has to be added to .gitignore or not, as it can be distracting for the 

About the real-data, I'm updating the wiki page with some examples!

**Comment by rougier** [comment]
Still, you can modify the index.rst file since it is the master file (from you conf.py). Not much is needed but the current content is rather minimal.

**Comment by SebastianoF** [comment]
Done! I'm not sure if it will be overwritten in re-creating the documentation with Sphynx. Will try and find another solution to make this part of the documentation more talkative!

**Comment by rougier** [comment]
I think the doc is in rst format and you used markdown for links. You need to modify them as:

[text](link) -> `text <link>`_

Apart from that, I think you're good. I would personally extend the index a little bit but it's up to you at this point.

**Comment by SebastianoF** [comment]
Closing for now.
Feel free to re-open for further suggestions in this thread. Thanks
