### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by rougier** [SebastianoF/bruker2nifti#23]
Can you add the DOI  for the two references in the bibliography?

Also, "Mattew Brett" -> "Matthew Brett"

**Comment by SebastianoF** [comment]
Typo corrected, thanks again.
The paper cox2004sort has no DOI, or no DOI I could find via the link https://www.crossref.org/guestquery/
I added the web link. Also the second reference had no DOI so I changed to an equivalent publication provided with a DOI.

**Comment by rougier** [comment]
New PDF is missing from the repo.

**Comment by SebastianoF** [comment]
About the pdf, wanted to ask if there is an automatic way of creating it from the .md.

I saw in many others JOSS submitted repo that the pdf is not present in the repo, but there is a link that provides a pdf obtained in some sort of standard template.

e.g.
[http://joss.theoj.org/papers/e40b3701ae4f96e1da1caedddafa121a](http://joss.theoj.org/papers/e40b3701ae4f96e1da1caedddafa121a)
[https://github.com/dhermes/bezier](https://github.com/dhermes/bezier)

Do I have to provide the pdf as well, inside the repo? Sorry this is my first JOSS submission.

**Comment by rougier** [comment]
And this is my first review... I don't know actually. We can keep it as it is, I can read the .md.
