### ISSUE TITLE
Error reading DWI data: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by r03ert0** [SebastianoF/bruker2nifti#25]
Hello,
Thank you for your work!
I'm trying to use bruker2nifti to convert DWI data, but I get the following error:

```
Traceback (most recent call last):
  File "//anaconda/bin/bruker2nifti", line 11, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/bruker2nifti/parsers/bruker2nii.py", line 91, in main
    study_name=args.study_name)
  File "//anaconda/lib/python2.7/site-packages/bruker2nifti/converter.py", line 58, in __init__
    self._get_scans_attributes()
  File "//anaconda/lib/python2.7/site-packages/bruker2nifti/converter.py", line 75, in _get_scans_attributes
    _study_name = get_subject_name(self.pfo_study_bruker_input).replace(' ', '_')
  File "//anaconda/lib/python2.7/site-packages/bruker2nifti/_getters.py", line 53, in get_subject_name
    visu_pars = bruker_read_files('visu_pars', pfo_study, sub_scan_num=list_scans[0])
IndexError: list index out of range
```

I installed bruker2nifti using `pip`, and his is the command line I used (it shows the structure of my bruker data directory):

```
$ bruker2nifti -i ~/Documents/ferret/data/raw-data/F01_Adult/dwi/10/ -o ~/Desktop/test/
/
    .DS_Store
    acqp
    AdjStatePerScan
    method
    pulseprogram
    spnam0
    spnam23
    spnam26
    uxnmr.par
pdata/
    .DS_Store
    1/
        .DS_Store
        2dseq
        d3proc
        id
        meta
        procs
        reco
        roi
        visu_pars
    2/
        2dseq
        d3proc
        id
        meta
        procs
        roi
        visu_pars
```

The data I would like to convert is inside /pdata/1/.

I looked into the code, and bruker2nifti looks at some point for orientation data in a variable called `VisuParseOrientation`, but in my `visu_pars` the only variable that seems to have an orientation matrix (repeated as many times as there are slices) is `VisuCoreOrientation`. Maybe that's the problem?

Thanks in advance!

**Comment by SebastianoF** [comment]
Hi! Thanks for the feedback. I may have improved the output for these cases in the next release.
`bruker2nifti ` must have as input a Bruker study (the folder with the subfolder numbered from 1 to n). If you want to convert a single study try with `bruker2nifti_scan`.
Let me know if it works, as the issue you pointed out may be another issue!
Which ParaVisoin version are you using?

**Comment by SebastianoF** [comment]
... And yes, there is a bug in the CLI anyway. A new version will be soon released. Please use the development version (see wiki to install) or use the GUI of the stable(?) release.
Sorry for the issues!

**Comment by r03ert0** [comment]
Thank you Sebastiano!

compiling the development version as indicated in the wiki did the job. Now, when I pass this command `$ bruker2nifti -i ~/Documents/ferret/data/raw-data/F01_Adult/dwi/ -o ~/Desktop/test/` the conversion produces .nii.gz files for all my scans \o/

The result is, however, flipped in the superior-inferior axis. Is this related to the conversion or could it be an error during the scanning? Should I fiddle with the Head_supine/prone parameters?

Here's a screenshot of the result:

<img width="994" alt="screen shot 2017-08-14 at 21 22 57" src="https://user-images.githubusercontent.com/2310732/29287947-42ea9ece-8137-11e7-8053-94ab9cc37a60.png">

The small panes on the right show the sup/inf inversion.

**Comment by SebastianoF** [comment]
Hi Roberto,
This is interesting!

It is not unusual to put the ex-vivo sample upside-down in the scanner, and there may be no way to know it from the parameter files. Of course only swapping sup/inf, will swap left/right, so this will need an inversion of the signs of the RL axis.

Try to play with the Head_supine/prone, changing the default `frame_body_as_frame_head` in `_utils.compute_affine_from_visu_pars`, while keeping `keep_same_det` to True and let me know if changing the default work. 

If you can, please send me one image sample or the visu_pars privately, if not having restrictions. I will try, in the near future, to see what I can do to integrate your case.

In the meantime, for your data, there is post-processing workaround to solve the problem using `fslorient` from FSL.
Should be similar to 

```
import os

cmd = ''' cp {0} {1};
                      fslorient -deleteorient {1};
                      fslswapdim {1} z y -x {1};
                      fslorient -setqformcode 1 {1};
                      fslreorient2std  {1}'''.format(pfi_in, pfi_out)
os.system(cmd)
```
where pfi = path to file, and where fsl must be installed in your computer.
You can check the fsl commands meaning online. fslswapdim return a warning if it swaps the sign determinant of the q-form.

In case you want to change it manually you can use ITK-snap tools ->reorient image

**Comment by r03ert0** [comment]
if i swap the mri data using fsl like that, should i also change the
bves/bvals?

**Comment by SebastianoF** [comment]
Yes

**Comment by r03ert0** [comment]
you are right : )
i'll create another issue. thank you!
