### ISSUE TITLE
Automatic version string generation fails on Travis

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#26]
On [Travis](https://travis-ci.org/SebastianoF/bruker2nifti/builds) the automatic version string generation based on the last Git-tag is broken.

Check [this build](https://travis-ci.org/SebastianoF/bruker2nifti/jobs/264287167) for an example.
This was build nr. 36 and this issue started happening at build nr. 35, where however only MD file changes were introduced.

**Comment by SebastianoF** [comment]
The automatic version string generation based on the last Git-tag was probably not a good idea in this case as it will not work when the version is called from outside the code directory.
Probably Travis_CI failed for that reason. 

Still trying to find a solution to write the version in the __init__.py as the __version__ variable that is robust enough, that does not require any manual intervention and that is based on the git tag of the repo.

**Comment by dzhoshkun** [comment]
We can implement a Git hook to do that. The hook would:
1. run the `git describe` command
1. format the version string accordingly, and
1. insert it into the `__init__.py` file as the `__version__` variable.

I can investigate this when I have time a bit later.

**Comment by dzhoshkun** [comment]
Unfortunately [the pre-receive hooks needed for this task are a GitHub enterprise (paid) feature](https://github.com/github/platform-samples/tree/master/pre-receive-hooks).

But there's another way to solve this problem. It will consist of two paths:

* Obtaining the version from within the repository folder: straightforward by calling `git describe` from within `bruker2nifti`
* Obtaining the version from within a pip-installed `bruker2nifti`: [using `pkg_resources.get_distribution()`](https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/blob/dev/niftynet/utilities/get_niftynet_version.py#L21)

@SebastianoF Let me know what you think. If you like this approach, I'm happy to implement it and submit a pull request.

**Comment by SebastianoF** [comment]
Hey! Still don't get why the attribute `cwd=` of `subprocess.check_output` does not work as it should... The method you proposed seems convoluted, but if it works don't se why not!

**Comment by dzhoshkun** [comment]
The rationale for this method is the support for version fetching on different installation types.  `pkg_resources.get_distribution()` looks like the standard way to fetch information about pip-installed packages. Calling `git describe` on the other hand has two use cases:
1. compose the version automatically **when bundling a pip installer**
1. compose the version automatically from within a Git repo clone

You can also opt for keeping the manually updated version variable, if your preference is to keep the source code simpler. There might be other ways of doing this, but the above approach is the only one I can think of right now.

I don't get why `cwd=` has suddenly stopped working, either. On a related note, [the current implementation assumes that the `bruker2nifti/__init__.py` file resides in a Git clone](https://github.com/SebastianoF/bruker2nifti/blob/42eafbd7cae2fb08b6731be4141306d7810edee2/bruker2nifti/__init__.py#L11), which it is not following a pip installation. So it will fail when the user tries to fetch the version after a regular `pip install bruker2nifti`

**Comment by dzhoshkun** [comment]
After our offline discussion we agree that fully automating the version string generation introduces too much complexity for the scale of this project. So closing this issue.
