### ISSUE TITLE
Converted MRI is oriented incorrectly: how to fix the orientation of the MRI and bvecs/bvals?

### ISSUE THREAD

**Issue by r03ert0** [SebastianoF/bruker2nifti#27]
After running the conversion using the developer version (see wiki to install), the resulting MRI data is oriented incorrectly. Here's the result:

<img width="994" alt="screen shot 2017-08-14 at 21 22 57" src="https://user-images.githubusercontent.com/2310732/29287947-42ea9ece-8137-11e7-8053-94ab9cc37a60.png">

Sebastiano suggested in issue #25 changing the `frame_body_as_frame_head` from `False` to `True` in the function `compute_affine_from_visu_pars` in _utils.py. The result is still oriented incorrectly, like this:

<img width="994" alt="screen shot 2017-08-15 at 21 03 51" src="https://user-images.githubusercontent.com/2310732/29331774-e4fbf516-81fd-11e7-92b5-9a31539eedf7.png">

As Sebastiano mentioned, it should be possible to fix the orientation problem using FSL like this:

```
import os

cmd = ''' cp {0} {1};
                      fslorient -deleteorient {1};
                      fslswapdim {1} z y -x {1};
                      fslorient -setqformcode 1 {1};
                      fslreorient2std  {1}'''.format(pfi_in, pfi_out)
os.system(cmd)
```

Is there a tool that would allow me to apply the same transformation to the bvecs/bvals data? [Probably it would be possible to implement that functionalitity directly in the converter? maybe something like an `-apply_transformation` switch?]

thank you very much in advance!

**Comment by SebastianoF** [comment]
Interesting, please post as well the affine matrices related to the two screenshots (in that order).

**Comment by r03ert0** [comment]
Here's the affine matrix for the 1st one (superior/inferior inversion):

```
Q-Form Code = 2
S-Form Code = 1
Quaternion Parameters:  b = 0.0  c = 0.0  d = 1.0
Quaternion Offsets:  x = 14.4  y = 19.2  z = -15.48
S-Form Parameters X: -0.24, 0.0, 0.0, 14.4
S-Form Parameters Y: 0.0, -0.24, 0.0, 19.2
S-Form Parameters Z: 0.0, 0.0, 0.24, -15.48
```

And for the second one (sagittal 90º rotation):

```
Q-Form Code = 2
S-Form Code = 1
Quaternion Parameters:  b = -0.70711  c = 0.0  d = 0.0
Quaternion Offsets:  x = 14.4  y = 19.2  z = -15.48
S-Form Parameters X: 0.24, -0.0, -0.0, 14.4
S-Form Parameters Y: 0.0, 0.0, 0.24, 19.2
S-Form Parameters Z: 0.0, -0.24, 0.0, -15.48
```

(I'll try to upload the data somewhere visible, but it'll take some time: 780MB)

**Comment by SebastianoF** [comment]
Thanks, will look at them soon. 
It seems that the Head_Prone is not behaving as supposed. 
Will dig again in the manuals and take a look at it again before next week.
In the meantime, if you need to quickly modify the orientation and the b-vects, I just committed a new function apply_orientation_matrix_to_image. You can use it as follows:

```
from bruker2nifti._utils import apply_orientation_matrix_to_image as appl
import numpy as np

appl('im1_DWI.nii.gz', np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0], [0,0,0,1]]), pfo_output='/Users/sebastiano/Desktop/test_header/zzz', pfi_b_vects='im1_DWI_DwGradVec.txt')
appl('3301_T1.nii.gz', np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0], [0,0,0,1]]), pfo_output='/Users/sebastiano/Desktop/test_header/zzz', pfi_b_vects='im1_DWII_DwGradVec.txt')

```

**Comment by r03ert0** [comment]
thank you very much! having that function accessible through python is great!

**Comment by SebastianoF** [comment]
apply_orientation_matrix_to_image has been removed with the latest commit for the reasons discussed in #30, and as you have it on your local branch. 
An analogous method can be found in the work in progress repository [LabelsManager](https://github.com/SebastianoF/LabelsManager)
