### ISSUE TITLE
-correct-slope does not have any effect

### ISSUE THREAD

**Issue by r03ert0** [SebastianoF/bruker2nifti#28]
I converted a DWI volume without using the `-correct-slope` switch and then using it, and the results are exactly the same. Both volumes are still in `int`, and if I sample a value in a specific direction at a specific x, y, z coordinate, the values are identic. The gz compressed file sizes are also the same.
These are the commands:

```
$ bruker2nifti -i ~/Documents/data-annex/ferret/data/raw-data/F01_Adult/dwi/ -o ~/Desktop/F01_Adult/
```

```
$ bruker2nifti -i ~/Documents/data-annex/ferret/data/raw-data/F01_Adult/dwi/ -o ~/Desktop/F01_Adult/ -correct_slope
```

**Comment by SebastianoF** [comment]
Argh, another bug! Thanks for reporting it. Please reopen the thread if you will have problem again on this issue.

**Comment by r03ert0** [comment]
It still produces the same uncorrected data. I think one reason may be lines 121-126 in _cores.py:

```
        if is_dwi:
            # Force to not correcting the slope, if true. Diffusion weighted images must be slope corrected before the
            # DTI analysis. They will be to heavy otherwise.
            correct_slope = False
            # Force method to be parsed. Useful infos in this file to process the DWI.
            get_method = True
```

However, even if I comment out the line `correct_slope = False`, the resulting file is the uncorrected one.

The function `slope_corrector` in _utils.py is being executed, and in my case, the if/elif section enters in the case starting in line 306:

```
        # each slice of the 3d image is multiplied an element of the slope consecutively
        if data.shape[2] == slope.shape[0]:
            for t, sl in enumerate(slope):
                data[..., t] = data[..., t] * sl
```

The `data` structure after slope_correction is effectively changed, but not saved...

**Comment by SebastianoF** [comment]
Thanks,

+ About not updating the variable after commenting the line `correct_slope = False`, I cannot reproduce the error you pointed out. May need more information, as your the .txt file parsed containing the slopes. will keep on doing some tests anyway.

+ As a choice, when it is about DWI, I chose to not correct for the slope.
Images will be too large afterwards (in my case something close to 300x300x300x200 voxels of float), and almost unmanageable. The result of the DTI processing was not having any significant improvement from this correction, so I suppressed the slope correction by default. 

In general among the many choices in converting from Bruker format (as the one you pointed out in #29 other than here), to make things less complicated, only some of them can be directly modified from the interface.

**Comment by r03ert0** [comment]
I may have found the reason why I don't see the effect of the visu slope correction:

In `_getters.py`, lines 200 (case "DTI") and 203 (case "Else"), `vol_data` is initialised from the original, uncorrected data in `img_data_vol`. This is not the case for the case "MSME", where `vol_data` is used. That may also explain why you see an effect and not me: you maybe are using "MSME" data for testing?

Changing those lines as follows fixes the issue for me:

```
                            elif fg_movie > -1:
                                # DTI
                                vol_data = vol_data.reshape(sh, order='F')
                            else:
                                # Else ?
                                vol_data = vol_data.reshape(sh, order='F')
```

**Comment by SebastianoF** [comment]
Bug fixed, thanks for your contributions!
