### ISSUE TITLE
Conversion fails for specra sequences

### ISSUE THREAD

**Issue by mediumspiny** [SebastianoF/bruker2nifti#34]
The medical imaging team at Radboud UMC have developed some new sequences that give data in Paravision 6 format and they have been having trouble using your Bruker2nifti python converter on the new sequences. Debugging the (very nicely written) code, conversion fails for sequences that generate spectra. In the method file these spectra have:

##$Method=<Bruker:PRESS>

Conversion fails in _getters.nifti_getter line 151 :

if not ['mm', ] * len(visu_pars['VisuCoreSize']) == visu_pars['VisuCoreUnits']:

This fails because visu_pars['VisuCoreSize’] is a float and therefore does not have a length. In fact, visu_pars['VisuCoreUnits'] = 'ppm' and these cannot be converted to a nifti at all. To get round this I have put the following in _cores.scan2struct (Line 82);

        if not isinstance(visu_pars['VisuCoreSize'], np.ndarray):
            warnings.warn("\nWarning, VisuCoreSize is not an array\nCannot convert\n")
            return None

ThiS returns to converter.convert_scan where I have changed line 135 from;

if not struct_scan == 'no data'

to:

if not struct_scan == None:

This now skips those spectrum scans that cannot be converted, although sub-folders do still get created for them. There are probably more elegant ways to do this, such as skipping the conversion entirely if method.Method == ' BRUKER:PRESS' but I wanted to make as few changes as possible to your code.

Regards.

Martin

**Comment by SebastianoF** [comment]
Hi!
Thanks for the feedback. 
Apart from the PRESS customised sequence, the fact that I was asking for the `len` of something could have not been an array was a bug. Moreover the `'no data'` attribute was an old string returned in a previous version of the converter. A bug as well. It is to me more elegant to fix as you proposed!
Close the issue for now, feel free to reopen if some problem will arise.
Will soon release pip-installable new patch with the updates.

Thanks again! 
Let me know if you will have problems with the orientation, as it seems quite an hot topic...

**Comment by mediumspiny** [comment]
Thanks Sebastiano. I will tell our imaging people to download the new version and try it out.
