### ISSUE TITLE
Folders not made in Windows

### ISSUE THREAD

**Issue by mediumspiny** [SebastianoF/bruker2nifti#35]
Hi,

Some people here at Radboud UMC have been using the converter under Windows. Unfortunately, it does not create the output folders as it does under Mac or *nix. This is due to a couple of Windows specific things. First, the path separator should work whether / or \ is used. But Windows does not seem to like it when a mix of the two is used and this is what tkFileDialog.askdirectory seems to do. So in open_gui.py line 105 you have:

    def button_browse_callback_pfo_output(self):
        filename = tkFileDialog.askdirectory()

and the filename produced here does not work in converter.py line 124:

                os.system('mkdir -p {}'.format(pfo_output_converted))

seemingly because of the mix of file separators. I added on line to the button callback:

        filename = path.abspath(filename)
and that required an additional import:
          from os import path

Additionally, the mkdir -p flag does not work in Windows. So I changed the line to make the folder in converter.py line 124 to:

        if create_output_folder_if_not_exists:
            if "win" in platform.lower():
                os.system('mkdir {}'.format(pfo_output_converted))
            else:
                os.system('mkdir -p {}'.format(pfo_output_converted))
That also requires an additional import:
      from sys import platform
It now seems quite happy in Windows.

Regards.

Martin

**Comment by SebastianoF** [comment]
Thanks!
Integration made. Only one difference was that `platform.lower()` on mac returns `darwin`. So I opted for `os.name.lower()` instead. Close the issue for now, please let me know if you will have further issues on windows.
