### ISSUE TITLE
Offset should be implemented in case of quantitative scan types

### ISSUE THREAD

**Issue by gdevenyi** [SebastianoF/bruker2nifti#36]
For quantitative scan types, the exact value of a voxel could have a interpretable meaning, and be comparable across subjects. As such, the slope and offset correction are essential so the "true" value is stored in the output nifti image.

Note, as of now I haven't seen a non-zero (0) value for offset in any scan from my PV5.1 system.

**Comment by SebastianoF** [comment]
Thanks, 
 On this side I have no data as well with non-zero offset, anyway offset correction added to the dev branch and integrated in the GUI. Issue open until integration in master. Will happen soon in the next patch/verson.
