### ISSUE TITLE
Slope correction disabled for DTI?

### ISSUE THREAD

**Issue by gdevenyi** [SebastianoF/bruker2nifti#39]
Is this as intended? I'm a bit confused why this might be:
https://github.com/SebastianoF/bruker2nifti/blob/a8ac49c23f309a1063f816bb772d143d53563983/bruker2nifti/_cores.py#L128-L133

**Comment by gdevenyi** [comment]
I've been tracking down "bad" FA maps (lots of voxels > 1) being produced from some data collected on PV5.1 (this is the same data that triggered the float inf bug, float export was another test, so far its not clear float reconstruction can actually produce a complete dataset). I was trying to compare conversions with and without slope correction only to find that both exports were identical.

Do you have a ref for the tensor fitting being invariant (I am by no means a DWI/DTI guy)? If this is the case, I believe its case closed on the original sequence not having enough SNR.

As far as the code is concerned here, I think the right thing problematically is to emit a warning regarding the wasted effort of slope correcting DWI data. I think silently ignoring a setting is the worst choice.

**Comment by SebastianoF** [comment]
If you have a single slope for all the slices (only case I saw so far) the DT fitting is invariant for a scaling factor. If you have a different slope for every time-point, then a quick way to re-apply the slope in a post processing can be:

`
import numpy as np
import nibabel as nib

from LABelsToolkit.tools.aux_methods.utils import eliminates_consecutive_duplicates
from LABelsToolkit.tools.aux_methods.utils_nib import set_new_data
from bruker2nifti._utils import data_corrector

def slope_corrector_path(slopes_array, path_im_input, path_im_output, eliminate_consec_duplicates=False):
    """
    Correct for the slope from the path of the elements
    :param slopes_array:
    :param path_im_input:
    :param path_im_output:
    :param eliminate_consec_duplicates:
    :return:
    """
    im_input = nib.load(path_im_input)
    # slopes = np.loadtxt(slopes_txt_path)
    if eliminate_consec_duplicates:
        slopes_array = np.array(eliminates_consecutive_duplicates(list(slopes_array)))
    data_output = data_corrector(im_input.get_data(), slopes_array, kind='slope')
    im_output = set_new_data(im_input, data_output)
    nib.save(im_output, path_im_output)
    msg = 'Scaled image saved in ' + path_im_output
    print(msg)
`
where LABelsToolkit is another repository I created for image processing.

Will add a flag for the next release of the converter, asking the user to specify this part.

**Comment by SebastianoF** [comment]
P.S. Do you have bad FA in the brain tissue or only on bones, eyes, and non-brain tissue?

**Comment by gdevenyi** [comment]
This is some post-postmortem tissue, no bones or such. Based on your feedback I think the scan procedure has produced data with too low an SNR.

Thanks for your help.
