### ISSUE TITLE
Add utility commands to pip installer for command line usage

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#4]
Currently bruker2nifti is run via `python parsers/bruker2nii.py`. We can add a [`console_scripts` entry point](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) which will allow the (pip-installed) package to run using for instance a command like `bruker2nifti`. We can do the same for the GUI app as well.

**Comment by SebastianoF** [comment]
Done and pushed to the repo. Not yet uploaded to Pypi. Coming soon! 
Thanks for the help on this!
