### ISSUE TITLE
qform/sform defaults?

### ISSUE THREAD

**Issue by gdevenyi** [SebastianoF/bruker2nifti#44]
Based on my reading of https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform.html

The data that comes out of bruker2nifti should be qform > 0 and sform = 0, since the data after conversion is in the scanner coordinate system space.

The default config doesn't appear to follow this standard.

Is the sform currently encoding something? If so, what?

**Comment by SebastianoF** [comment]
Deafults are qform_code=1 and sform_code=2.
http://nipy.org/nibabel/nifti_images.html#the-sform-affine
Sform and qform are encoding the same transformation after the conversion. 

By then I believed it was the option that was leaving most freedom to the next user. 
In case there is a template available, you can just update the sform to the transformation from original coordinates to the template coordinates. 
If no template is available then the scanner reference works as some sort of template orientation.
In the end I have never used it myself in my study, as different modalities of the same subject that I have received where not aligned with each others...
