### ISSUE TITLE
Handling "Warning, VisuCoreSize in VisuPars parameter file animal2/39/pdata/1 is not a list or a vector in. The study cannot be converted."

### ISSUE THREAD

**Issue by demianw** [SebastianoF/bruker2nifti#45]
Hello! 

Do you have an idea of how to handle this error?

```
Converting experiment 39:

FRAME BODY True
UPSIDE DOWN True
pdata/
    1/
        visu_pars
        reco
        meta
        procs
        id
        d3proc
        2dseq
/Users/dwasserm/anaconda/envs/root3.7/lib/python3.7/site-packages/bruker2nifti/_cores.py:90: UserWarning:
Warning, VisuCoreSize in VisuPars parameter file animal2/39/pdata/1
is not a list or a vector in. The study cannot be converted.

  "".format(jph(pfo_scan, 'pdata', id_sub_scan)))
```

**Comment by SebastianoF** [comment]
Hi!
Yes, the attribute VisuCoreSize in the file VisuPars is a float, but we expect it to be a list or a vector. (The formatting of the error message is printed wrongly.)
Never understood why this can happen sometimes, and what to do with a scan that is not providing spatial dimension. 
The quick fix is to change manually its value from something that is compatible with the dimensions of the image, directly in the visu pars file. E.g. from
```
##$VisuCoreSize=( 1 )
3.14
```
to 
```
##$VisuCoreSize=( 2 )
45 56
```
Where 45 x 56 is the number of voxels you should have in the vector stored under "2dseq".
