### ISSUE TITLE
DTI Tensor Reconstruction Support

### ISSUE THREAD

**Issue by hookeba** [SebastianoF/bruker2nifti#47]
Dear Dr. Ferraris

I have enjoyed using bruker2nifti for my research.  I would like to know if it will support conversion of DTI tensor reconstruction.  I would like to examine ParaVision’s diffusion quantities including the trace weighted image for ADC map calculations.  Thank you for your assistance.

Respectfully yours

Bradley A. Hooker

**Comment by SebastianoF** [comment]
Dear Dr. Hooker,

Many thanks for your kind message, I'm very glad I could be of some help.

About your question, the efforts on bruker2nifti ends where the conversion ends, so there is no DTI fitting, or other post-processing after the conversion. 

Typically I had been using [nilabels](https://github.com/nipy/nilabels) for re-orientation and the well established FSL for tensor fitting. You can find an example of pipeline where bruker2nifti is combined with FSL in the repository [RabbitBrainAnalysis](https://github.com/gift-surg/RabbitBrainAnalysis). 
Hope it helps.

Best Regards,
Sebastiano Ferraris

**Comment by hookeba** [comment]
Sebastiano

Thank you for your informative response.  I will examine the RabbitBrainAnalysis repository for an example of bruker2nifti/FSL integration.

Brad

**Comment by SebastianoF** [comment]
Cool! Feel free to pick up what you need from `main_pipeline/A1_convert_and_clean` and `main_pipeline/A2_process_modalities`.
