### ISSUE TITLE
Bundle the test suite with the pip installer

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#5]
The [`setuptools` API](http://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords) now supports a `test_suite` capability.
We can investigate how this can be used for bundling the test suite into the pip installer.

**Comment by SebastianoF** [comment]
Sounds interesting, although the test requires some load of data in ParaVision format to convert. I guess, this should be downloaded with pip at the moment of the installation to make it work. 

An external benchmarking, as discussed offline with @neurolabusc, also to compare other converters, and to have a dataset for tests, can be an optimal solution.

**Comment by dzhoshkun** [comment]
re "this should be downloaded with pip at the moment of the installation"

I wouldn't recommend doing that. It unnecessarily creates a dependency between your pip installation and the data download. For instance imagine the data download goes wrong, and the pip installation just fails.

It can be configured to download the data when the test command is run.

**Comment by SebastianoF** [comment]
Agree. My preference is for the external benchmarking.
re "It can be configured to download the data when the test command is run." 
This can be done already  downloading the repo... Is there any benefit in linking it to the pip installation?

**Comment by dzhoshkun** [comment]
@SebastianoF "This can be done already downloading the repo" is not clear to me. Is the data included as part of a repo?

**Comment by dzhoshkun** [comment]
I've had another look, and noticed the `test_data` folder. If with "This can be done already downloading the repo" you mean that folder, it's possible to bundle it as part of the pip installer as well. See the [`package_data` keyword](https://docs.python.org/2/distutils/setupscript.html#installing-package-data).

The benefit of `package_data` is that the user doesn't have to go through a separate data download. `package_data` is suitable for small datasets that do not make the pip installer fat. It "installs" data together with the software and you can later on [fetch that data from within Python without any input from the user such as the absolute file path to the data](https://github.com/gift-surg/endocal/blob/master/endocal/__init__.py#L144).

Also please note the information about the `test_suite` keyword in the description of this issue. (I've never used this before, but) I reckon this can be used for bundling your tests provided in the `test` directory into the pip installer. If you think this is useful, I'm happy to help set it up.

**Comment by SebastianoF** [comment]
Given the heavy data weights possibly involved, and being purposes of this repo the conversion it may be better to opt for future external benchmarking. Will reopen and update when/if available.
Thanks for the help!!
