### ISSUE TITLE
Converter to nifti officially released in latest Paravision patch - update Readme

### ISSUE THREAD

**Issue by SebastianoF** [SebastianoF/bruker2nifti#55]
Great news:
From ParaVision 360 with the latest patch 1.1, bruker scanner can export acquired images to nifti format 
http://bruker.telemaxx.net/student/Distribution_Note_and_Installation_GuidePv360V1.1.pdf

Readme will be shortly udpated with this one as first option for future users. 
Not so sure the native PV converter works retroactively for old acquisitions.

**Comment by gdevenyi** [comment]
I have complete confidence that Bruker has implemented NIFTI conversion according to the standard. Like SPM.
