### ISSUE TITLE
Current tests master fails for Python 2.7

### ISSUE THREAD

**Issue by SebastianoF** [SebastianoF/bruker2nifti#57]
```

a = PosixPath('/tmp/pytest-of-circleci/pytest-0/test_read_subject0')
p = ('bru_banana',)
path = PosixPath('/tmp/pytest-of-circleci/pytest-0/test_read_subject0')
b = 'bru_banana'

    def join(a, *p):
        """Join two or more pathname components, inserting '/' as needed.
        If any component is an absolute path, all previous path components
        will be discarded.  An empty last part will result in a path that
        ends with a separator."""
        path = a
        for b in p:
            if b.startswith('/'):
                path = b
>           elif path == '' or path.endswith('/'):
E           AttributeError: 'PosixPath' object has no attribute 'endswith'

/usr/local/lib/python2.7/posixpath.py:70: AttributeError
________________ ERROR at setup of TestMetadata.test_read_recon ________________
```
Investigations in progress...!

**Comment by jathpala** [comment]
Hi Sebastiano, what are your plans with regards to python 2.7 end of support at the end of the year?

**Comment by SebastianoF** [comment]
I really like fixtures and would like to move in the direction you have started. At the same time research domain can be slow to upgrade, and removing support for 2.7 may cause trouble... 

Probably I will be doing another patch release with python 2.7 compatible at the end of the year (version 1.0.something) and then I would drop the 2.7 support from next year onward. If you have any suggestion or comment please do feel free to open a new issue for further discussions!
