### ISSUE TITLE
v1.0.3 "Sample upside down" and "Frame body as frame head" both default to true for command-line

### ISSUE THREAD

**Issue by gdevenyi** [SebastianoF/bruker2nifti#58]
Using the command-line bruker2nifti, default operation has changed, the addition of the "Sample upside down" and "Frame body as frame head" both default to true:

```
bruker2nifti -i /data/chamal/Bruker_7T_animal_scans/nmr/20190915_MCH_MIA_111_21.Vi1/ -o . -correct_offset -correct_slope
/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Converter input parameters: 
-------------------------------------------------------- 
Study name           : 20190915MCHMIA11121
List of scans        : ['1', '2', '3', '4', '5', '6', '7', '8', '9']
List of scans names  : ['20190915MCHMIA11121_1', '20190915MCHMIA11121_2', '20190915MCHMIA11121_3', '20190915MCHMIA11121_4', '20190915MCHMIA11121_5', '20190915MCHMIA11121_6', '20190915MCHMIA11121_7', '20190915MCHMIA11121_8', '20190915MCHMIA11121_9']
Output NifTi version : 1
Output NifTi q-form  : 1
Output NifTi s-form  : 2
Save human readable  : True
Correct the slope    : True
Correct the offset   : True
-------------------------------------------------------- 
Sample upside down         : True
Frame body as frame head   : True
-------------------------------------------------------- 
```

**Comment by SebastianoF** [comment]
Thanks! What is the behaviour you expect to see? Can you open a PR?

**Comment by gdevenyi** [comment]
You added the upside down and frame body as frame head settings, but they're turned on as default, so, upgrading from 1.0.2 to 1.0.3 changes the output orientations.
```
Sample upside down         : True
Frame body as frame head   : True
```

First, this is a breaking change, and shouldn't be according to semver https://semver.org/, second, adding the options, ``-sample_upside_down`` and ``-frame_body_as_frame_head`` make these false, and fix things, so I guess there's a bug somewhere?

```
bruker2nifti -frame_body_as_frame_head -sample_upside_down -i /data/chamal/Bruker_7T_animal_scans/nmr/20190915_MCH_MIA_111_21.Vi1/ -o .
/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Converter input parameters: 
-------------------------------------------------------- 
Study name           : 20190915MCHMIA11121
List of scans        : ['1', '2', '3', '4', '5', '6', '7', '8', '9']
List of scans names  : ['20190915MCHMIA11121_1', '20190915MCHMIA11121_2', '20190915MCHMIA11121_3', '20190915MCHMIA11121_4', '20190915MCHMIA11121_5', '20190915MCHMIA11121_6', '20190915MCHMIA11121_7', '20190915MCHMIA11121_8', '20190915MCHMIA11121_9']
Output NifTi version : 1
Output NifTi q-form  : 1
Output NifTi s-form  : 2
Save human readable  : True
Correct the slope    : False
Correct the offset   : False
-------------------------------------------------------- 
Sample upside down         : False
Frame body as frame head   : False
-------------------------------------------------------- 
```

I'm not sure where I need to change things yet to fix this.

**Comment by gdevenyi** [comment]
Looks like the offending code is here:
https://github.com/SebastianoF/bruker2nifti/commit/63eec276844434627f93ce32f862df2a18e5ecc0#diff-c63100f34d40b1567cf44a7d6c0564caR84-R93

Where the command line does "store_false" so the value defaults to true, this conflicts with the default set for the scan2struct

**Comment by gdevenyi** [comment]
Indeed, the GUI sets the correct defaults.

**Comment by gdevenyi** [comment]
https://github.com/SebastianoF/bruker2nifti/commit/e517928e3f46af11abb33b81fe0fe171b9643671 did not change -frame_body_as_frame_head

**Comment by SebastianoF** [comment]
I merged your PR. Sorry I did not see it before. Pelase let me know if master is now OK, and if you are willing to take care of reducing the code duplicate!

**Comment by SebastianoF** [comment]
(also please do add the issue number in the git commit message, so it will appear here!)

**Comment by SebastianoF** [comment]
As soon as I have green light from you, I can prepare a new release. Well spotted for the inconsistencies across version.

**Comment by gdevenyi** [comment]
Defaults are now back to normal.

I'd like to further improve the CLI, but I'll leave that for another PR, or maybe my student will get to it first.

**Comment by SebastianoF** [comment]
Great, thanks!!
And about your students, there would be also issue #53, for which I can provide guidance!
