### ISSUE TITLE
Consider publishing the API online

### ISSUE THREAD

**Issue by dzhoshkun** [SebastianoF/bruker2nifti#6]
For instance the [`skimage` API](http://scikit-image.org/docs/stable/api/api.html) looks very nice. There are freely available platforms for publishing API and docs online. See for example the [NumPy documentation on ReadTheDocs](https://readthedocs.org/projects/numpy/).

@SebastianoF This is another way of advertising bruker2nifti. The setup itself is minimal, but the source code needs to be properly documented. Once this is done, the API documentation can be generated automatically using [Sphinx](http://www.sphinx-doc.org/en/stable/). The documentation generation can also be automated, for instance a push to the repository can trigger it automatically.

Depends on #7

**Comment by SebastianoF** [comment]
I should add it to readthedocs.org. 
@dzhoshkun please send me info about how to run sphinx offline! Cheers!

**Comment by dzhoshkun** [comment]
@SebastianoF Have a look at this tutorial: http://docs.readthedocs.io/en/latest/getting_started.html

It includes getting started with Sphinx **and** also connecting the GitHub repository to ReadTheDocs

**Comment by dzhoshkun** [comment]
```
def run_apidoc(_):
    modules = ['a_list_of',
               'python_module_directories',
               'in_your_project']
    for module in modules:
        cur_dir = os.path.abspath(os.path.dirname(__file__))
        output_path = os.path.join(cur_dir, module, 'doc')
        cmd_path = 'sphinx-apidoc'
        if hasattr(sys, 'real_prefix'):  # Check to see if we are in a virtualenv
            # If we are, assemble the path manually
            cmd_path = os.path.abspath(os.path.join(sys.prefix, 'bin', 'sphinx-apidoc'))
        subprocess.check_call([cmd_path, '-e', '-o', output_path, module, '--force'])

def setup(app):
    app.connect('builder-inited', run_apidoc)
```
Source: https://github.com/rtfd/readthedocs.org/issues/1139

**Comment by SebastianoF** [comment]
Done! bruker2nifti.rtfd.io
Thanks for the help(s)!

**Comment by dzhoshkun** [comment]
No worries!
