### ISSUE TITLE
        I Can not run bruker2nifti on mac

### ISSUE THREAD

**Issue by mpompilus** [SebastianoF/bruker2nifti#65]

**Comment by SebastianoF** [comment]
Perbacco!!

Would you give me any further info about it?
Are you running it in a virtualenvironment? 
What happens when you do `pip install bruker2nifti`?
Where does it crash?

**Comment by mpompilus** [comment]
Hello,

I  downloaded bruker2nift, the format of  "download zip" but I can start run it to convert

[X]



I could not get this part works

[X]
Would you please help me work it out?

Best,
Marjory





________________________________

**Comment by SebastianoF** [comment]
Hi Majory,
I can not see your screenshots.

So I would say, please do take a look at the [up and running for non python developers](https://github.com/SebastianoF/bruker2nifti/wiki/Up-and-running-for-non-Python-developers)

It may be slightly out of date, though with a bit of luck it may still work.
When doubleclicking on the launcher creator, or on the created launcher in the root folder, you may see error messages in the terminal that got automatically open.

Post here the error messages you find on the terminal if you find any.

Thanks!
Sebastiano

**Comment by SebastianoF** [comment]
If you are still in trouble, please let me know via email and we can arrange a skype/hangout/zoom phone call to set it to work... As it is, it ain't simple for me to know where to start troubleshooting...
You can find my email address under my profile.
Cheers

**Comment by SebastianoF** [comment]
Closing the issue for now. Feel free to re-open it again or to contact me directly for instructions. Cheers
