### ISSUE TITLE
Have you ever tried to convert CSI data to Nifti?

### ISSUE THREAD

**Issue by amirshamaei** [SebastianoF/bruker2nifti#66]
Hi all,
I am trying to convert Bruker CSI data to Nifti. Everything looks OK, except the excited CSI grid. How I can store it in Nifti? Do you think it is possible? should I use a sidecar file like json? how can I use PVM parameters for the excited grid in a way that matches with the affine matrix? 
I don't have access PV360, I am really curious how they store CSI in nifti format! in case you know, I appreciate your answer.
Sorry for this series of questions :) It may not relevant to the main subject of this repo (in case let me know), but I could not find any other place on the net to put my question.

**Comment by gdevenyi** [comment]
Hi @amirshamaei I don't think we've had access to a CSI dataset yet, so testing will be limited. If you would be willing to share an example that would be helpful.

It would also help if you could completely explain the experiment and what kind of output might be a useful format for you. I've never done CSI so I don't have an intuition as to how the final data should be formatted.

**Comment by amirshamaei** [comment]
@gdevenyi  Thank you. Absolutely, I will come back with a comprehensive example and explain what I have done so far. stay tuned :)

**Comment by gdevenyi** [comment]
I've also been working with https://github.com/BrkRaw/bruker which may be more comprehensive in terms of conversion at this point. We'd appreciate if you could give it a test and open up an issue there as well.

**Comment by amirshamaei** [comment]
Thank you @gdevenyi 
1. I tried BrkRaw today; It is really nice. I couldn't load my CSI data. I think It doesn't support it now.
2. I was working on JAVA Bruker API (https://github.com/isi-nmr/brukerapi-java). I think If we have a solution for CSI to nifti conversation, is it possible to implement it in your tool. isn't it?
3. I will create an issue in your repo.

**Comment by gdevenyi** [comment]
> I tried BrkRaw today; It is really nice. I couldn't load my CSI data. I think It doesn't support it now.

Ok

> I was working on JAVA Bruker API (isi-nmr/brukerapi-java). I think If we have a solution for CSI to nifti conversation, is it possible to implement it in your tool. isn't it?

Yes, that's a goal, an example data set (ideally with some with other contrasts collected at the same time) would help us get this working.

> I will create an issue in your repo.

:+1:

**Comment by amirshamaei** [comment]
As I promised, I bring an example of CSI data. I couldn't share the binary file (2dseq) for this specific data, but here you can find the Parameters files of the anatomical(MRI) and spectroscopic experiments. Download : [CSI to nifti example.zip](https://github.com/SebastianoF/bruker2nifti/files/5530286/CSI.to.nifti.example.zip)
Well, I summarized the key differences between files:

| VisuPars | CSI | MRI |
|:---:         |     :---:      |         :---: |
| Dim   | 3     | 2    |
| Size    | 2048, 16, 16       | 256, 256      |
| DimDesc | 3 | 2|
||Spec, Spa, Spa|Spa, Spa|
|Extent|9.99, 30, 35|30,35|
|unit|<ppm, mm, mm>|<mm, mm>|
|seq name|CSI|RARE|

Everything is clear for conversation to nifti except affine matrix and region of interest. In the following you can find my solution, but it is just my understanding of Bruker "magic" black box; so, I would really happy to hear your idea and oponion. 
1. To calculate the affine matrix, my solution is based on this library approach.
To calculate resolution matrix, I get rid of first element of size and extent matrix and add slice thickness(isn't it meaningless to have slice in MRSI data!?). Then the rest of calculation is exactly like the anatomical image, but with different resolution and voxel(pixel) size. 
So, for calculating qform matrix for CSI; we set qform_code to SCANNER_ANAT(1) which is aligned to scanner (or AlINED_ANT(2)? i am not sure, Correct me if i am wrong). 
here I depicted the idea:
![Presentation1](https://user-images.githubusercontent.com/56726574/98950972-f7560b00-24f9-11eb-9d5f-8921f20d7a94.jpg)
2. Excited voxels: this part is more challenging than previous. the excited voxel (voxels of interest) is smaller matrix; but with same resolution. but there was not any parameter in VisuPars file about it. I found information about it in PVM_VOXArrSize and ~_~Position in method file. however; i notice the number is not fit to VisuPars parameters. So, I used VoxelGradOrientation to convert them and then sum them up with half of VisuExtent elements. Right now, I have Position of VOI and resolution as well. 


| CSI affine matrix ||||
| :---: | :---: | :---: | :---: |
| -1.8750 |         0 |        0 |   13.1653 | 
|         0|         0|    2.0000|   16.5062| 
|         0|  -2.1875|         0|         0| 
|         0|         0|         0|    1.0000|

| Anatomical affine matrix ||||
| :---: | :---: | :---: | :---: |
|  -0.1172|         0|        0|   13.1653| 
|       0|        0|    2.0000|    16.5062| 
|    0|   -0.1367|         0,         0| 
 |         0|         0|         0|     1.0000| 

Position of VOI: [16.45,  19.33, 0]
Resolution of VOI : [25, 30, 2]

##$PVM_VoxArrSize=( 1, 3 )
30 25 2
##$PVM_VoxArrPosition=( 1, 3 )
-1.83466 1.45244 0

**if I calculate everything in a right way, so How i can store them in nifti format? any suggestion?**
** this post will be updated

**Comment by SebastianoF** [comment]
Hi @amirshamaei, sorry for the late reply. 

I agree the BrkRaw is the best place where to go, unless you want to create your CSI parser (do feel free to fork this repo, if it can be a starting point of any use - keeping in mind that it was developed for my MRI/DWI, versions PV5.1 and PV6 dataset, and it is far from being a complete converter).

I've never worked with CSI, but I asked around and heard that usually the data is converted to json and stored alongside the nifty (a sidecar file, as you said). It seems it is not possible to embed the signal in the nifti header in any reasonable way. Hope this helps.

**Comment by amirshamaei** [comment]
Hi @SebastianoF, 
> I agree the BrkRaw is the best place where to go, unless you want to create your CSI parser (do feel free to fork this repo, if it can be a starting point of any use - keeping in mind that it was developed for my MRI/DWI, versions PV5.1 and PV6 dataset, and it is far from being a complete converter).
Yes. I will implement a convertor for CSI data over BrkRaw, but at this stage, I will use this repo's approach for conversation.

> I've never worked with CSI, but I asked around and heard that usually the data is converted to json and stored alongside the nifty (a sidecar file, as you said). It seems it is not possible to embed the signal in the nifti header in any reasonable way. Hope this helps.
Thank you. So, I will create a JSON file, but the problem is that there is any standard to stick to it.

**Comment by SebastianoF** [comment]
There is no standard. 

I suggest to either write the minimal ad hoc code that is tested and works well only for your project, or to invest several months to set up a proper standard for CSI files, to be open sourced, versioned controlled and fully supported (involving the nifti community and as many labs and scanners manufacturers you may want).

Beware of anything in between, which may result in a deadly trap for you and for other possible users.
