### ISSUE TITLE
Installation issue on Macbook with apple M1 chip

### ISSUE THREAD

**Issue by javier-allende** [SebastianoF/bruker2nifti#69]
When I try to install the GUI on a MACbook with apple M1 chip, and MacOS Ventura 13.0. The GUI file does not appear, I get the following message in the installation:

/Users/Pelon/Downloads/bruker2nifti-master/setupper/run_setupper_MAC ; exit;    
Pelon@Javier-MacBookPro-2 ~ % /Users/Pelon/Downloads/bruker2nifti-master/setupper/run_setupper_MAC ; exit;

Creating virtual environment, installing the libraries and deactivating:

./setupper_MAC.sh: line 16: pip: command not found
./setupper_MAC.sh: line 17: virtualenv: command not found
./setupper_MAC.sh: line 18: venv/bin/activate: No such file or directory

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Any help on how to fix this is greatly appreciated

**Comment by gdevenyi** [comment]
This has nothing to do with apple M1, your python environment is incomplete.

**Comment by SebastianoF** [comment]
Hello!
The takeaway is:
```
./setupper_MAC.sh: line 16: pip: command not found
```
So you do not have a python installed from where you are starting the environment.
You would have the same issue if running the CLI or if running the command in any other way.

More info about dependencies in python can be found on this guide:
[https://www.fullstackpython.com/application-dependencies.html](https://www.fullstackpython.com/application-dependencies.html)

**Comment by SebastianoF** [comment]
More specifically to your question, you can follow the guide there:
```
https://www.freecodecamp.org/news/pip-command-not-found-mac-and-linux-error-solved/
```
The page suggest to check if `pip` in installed with:` python3 -m pip --version `

If not, then to go over this page [https://pip.pypa.io/en/stable/installation/](https://pip.pypa.io/en/stable/installation/) and follow the instrcutions.

**Comment by SebastianoF** [comment]
I'm closing the issue for now. Please open a new issue if you have any further question, or if something goes wrong after installing pip.
